LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := main

SDL_PATH := ../SDL

LOCAL_C_INCLUDES := $(LOCAL_PATH)/$(SDL_PATH)/include

# LOCAL_CFLAGS += -Wc++11-extensions

# Add your application source files here...
LOCAL_SRC_FILES := button.cpp shapes.cpp board.cpp tetris.cpp

LOCAL_SHARED_LIBRARIES := SDL2 SDL2TTF SDL2MIXER SDL2IMAGE

$(warning $(LOCAL_PATH))
$(warning $(TARGET_ARCH_ABI))

LOCAL_LDLIBS := -lGLESv1_CM -lGLESv2 -llog

include $(BUILD_SHARED_LIBRARY)


include $(CLEAR_VARS)
LOCAL_MODULE := SDL2
LOCAL_SRC_FILES := $(LOCAL_PATH)/SDLLibs/$(TARGET_ARCH_ABI)/libSDL2.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/SDL2/include
include $(PREBUILT_SHARED_LIBRARY)


include $(CLEAR_VARS)
LOCAL_MODULE := SDL2TTF
LOCAL_SRC_FILES := $(LOCAL_PATH)/SDLLibs/$(TARGET_ARCH_ABI)/libSDL2_ttf.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/SDL2_ttf/include
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := SDL2MIXER
LOCAL_SRC_FILES := $(LOCAL_PATH)/SDLLibs/$(TARGET_ARCH_ABI)/libSDL2_mixer.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/SDL2_mixer/include
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := SDL2IMAGE
LOCAL_SRC_FILES := $(LOCAL_PATH)/SDLLibs/$(TARGET_ARCH_ABI)/libSDL2_image.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/SDL2_image/include
include $(PREBUILT_SHARED_LIBRARY)